### ISSUE TITLE
KeyError: 'tree'

### ISSUE THREAD

**Issue by zchoi** [LibertFan/TAGS#1]
When I run this code, I got an error like this, please tell me how to solve this? I'm a little bit confused, thanks:

[1,0]<stderr>:Traceback (most recent call last):
[1,0]<stderr>:  File "train_pnsgd.py", line 579, in <module>
[1,0]<stderr>:    main(args)
[1,0]<stderr>:  File "train_pnsgd.py", line 217, in main
[1,0]<stderr>:    for batch in train_dataloader_t:
[1,0]<stderr>:  File "/src/data/loader.py", line 106, in __iter__
[1,0]<stderr>:    self.preload(loader_it)
[1,0]<stderr>:  File "/src/data/loader.py", line 117, in preload
[1,0]<stderr>:    self.batch = next(it)
[1,0]<stderr>:  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 551, in __next__
[1,0]<stderr>:    return self._process_next_batch(batch)
[1,0]<stderr>:  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 575, in _process_next_batch
[1,0]<stderr>:    raise Exception("KeyError:" + batch.exc_msg)
[1,0]<stderr>:Exception: KeyError:Traceback (most recent call last):
[1,0]<stderr>:  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
[1,0]<stderr>:    samples = collate_fn([dataset[i] for i in batch_indices])
[1,0]<stderr>:  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
[1,0]<stderr>:    samples = collate_fn([dataset[i] for i in batch_indices])
[1,0]<stderr>:  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataset.py", line 85, in __getitem__
[1,0]<stderr>:    return self.datasets[dataset_idx][sample_idx]
[1,0]<stderr>:  File "/src/data/pnsgd.py", line 410, in __getitem__
[1,0]<stderr>:    tree = self.txt_db[gt_txt_id]['tree']

**Comment by LibertFan** [comment]
You can replace the original text_db with the one in the url: [https://drive.google.com/drive/folders/1ZOK3jlcgGRifz8iw2-5vL89rIJcoYU3D?usp=sharing](https://drive.google.com/drive/folders/1ZOK3jlcgGRifz8iw2-5vL89rIJcoYU3D?usp=sharing)
